### ISSUE TITLE
unreadable buttons when using MaterialComponents theme

### ISSUE THREAD

**Issue by ligi** [Kunzisoft/AndroidClearChroma#16]
I am using the MaterialComponents theme to be able to e.g. use MaterialButton from the new support library 28.0.0 - unfortunately then the dialog buttons render badly:

![screenshot_1539612580](https://user-images.githubusercontent.com/111600/46956678-29d07800-d096-11e8-9852-5e13bb17cdd3.png)

I get the same behavior when using  android.app.AlertDialog instead of android.support.v7.app.AlertDialog in other places.

**Comment by J-Jamet** [comment]
Sorry for the response time, I was busy.
You can force the theme of the dialog with this code:

`<style name="Chroma.AlertDialog" parent="Theme.MaterialComponents.Light.Dialog.Alert"/>`

I will look if I can do the theme inheritance.

**Comment by J-Jamet** [comment]
Fixed in 2.1
