### ISSUE TITLE
Consider Listing on F-Droid

### ISSUE THREAD

**Issue by Grossdm** [Kunzisoft/AndroidClearChroma#17]
Please consider listing this app on [F-Droid.](https://f-droid.org/)

**Comment by J-Jamet** [comment]
The main product of the project is a library, the app is only here to have a sample, so what's the point to keep an app versioning in a store ?

**Comment by Grossdm** [comment]
Well, @J-Jamet, now that I understand that the app is only a sample I can see why you've chosen not to list it on F-Droid.
