### ISSUE TITLE
Problem with CMYK mode.

### ISSUE THREAD

**Issue by karol-202** [Kunzisoft/AndroidClearChroma#4]
When opening dialog in CMYK mode, sliders are initially at weird positions(without relation to current color). When I touch any slider, then color updates.
[Screenshot 1](https://drive.google.com/file/d/0B_6iiM_n3ztwaHBiY0lqNTdKcjQ/view?usp=sharing)
[Screenshot 2](https://drive.google.com/file/d/0B_6iiM_n3ztwLS1XMFpvelJJeDQ/view?usp=sharing)
Notice the same positions of the sliders and different colors.

**Comment by J-Jamet** [comment]
Thx for your reply. I will try to change the code in the week to make a new version that will handle the fragments and solve this color refresh problem. ;) The main code needs to be a bit refactored, I'll try to be fast.

**Comment by J-Jamet** [comment]
It's now OK with 1.7 version, but there is a lot of change in the code to stick to the standards, you will probably have to change the code of your application. Tell me if it's OK for you ?

**Comment by karol-202** [comment]
I updated the library to 1.7. CMYK mode still doesn't work, it may be caused by color conversion in CMYK.java.
However I noticed that CMYK255 works well, so it's OK for me.

**Comment by J-Jamet** [comment]
You're right, I was doing the bad tests, I'll fix it in the next version. ;)

**Comment by J-Jamet** [comment]
The code is refactored for CMYK and CMYK255 in version 1.8. ;)

**Comment by karol-202** [comment]
Now it works fine. :)
