### ISSUE TITLE
Orientation change

### ISSUE THREAD

**Issue by StephaneBg** [Kunzisoft/AndroidClearChroma#6]
Hello,
thanks for the library.

I create a ChromaDialog from a Fragment. The problem is that after a screen rotation the OnColorSelectedListener is not called.

**Comment by J-Jamet** [comment]
You're right, in fact it is called but not with the new activity created after orientation. So it's a normal way in fragment, so you have to use SupportFragmentManager to get the fragment in memory (with TAG) and link them with listener in new activity. I'll change the example in the sample. ;)
_(Et c'est cool de voir un français ;)_

**Comment by J-Jamet** [comment]
You can see the sample in [https://github.com/Kunzisoft/AndroidClearChroma/blob/master/sample/src/main/java/com/kunzisoft/androidclearchroma/sample/MainActivity.java](https://github.com/Kunzisoft/AndroidClearChroma/blob/master/sample/src/main/java/com/kunzisoft/androidclearchroma/sample/MainActivity.java)

(in fragment it's the same way, but with ChildFragmentManager)

```
private ChromaDialog chromaDialog;

@Override
protected void onCreate(Bundle savedInstanceState) {
    ...
    // Get fragment in memory
    chromaDialog = (ChromaDialog) getSupportFragmentManager().findFragmentByTag(TAG_CHROMA_DIALOG);
    // Assign current listener
    if(chromaDialog != null)
        chromaDialog.setOnColorSelectedListener(this);
    ...
}

yourButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // New initialization if it's first time or after validation
                if(chromaDialog == null) {
                    chromaDialog = new ChromaDialog.Builder()
                            .initialColor(color)
                            .colorMode(colorMode)
                            .indicatorMode(indicatorMode) //HEX or DECIMAL;
                            .setOnColorSelectedListener(MainActivity.this)
                            .setOnColorChangedListener(MainActivity.this)
                            .create();
                }
                chromaDialog.show(getSupportFragmentManager(), TAG_CHROMA_DIALOG);
            }
        });

@Override
    public void onPositiveButtonClick(@ColorInt int newColor) {
        ...
        // For new initinialization
        chromaDialog = null;
       ...
    }
```

**Comment by J-Jamet** [comment]
No need to redefine the listener in the 1.8 ;)
