### ISSUE TITLE
Exception: does not belong to this FragmentManager

### ISSUE THREAD

**Issue by mocle** [Kunzisoft/AndroidClearChroma#9]
I'm using this great library in a fragment and declaring the ChromaPreferences itself in a preferences xml file. But when i try to click on such a preference it always throws the exception:
```
java.lang.IllegalStateException: 
Fragment ChromaDialog{1e66cca #0 TAG_FRAGMENT_DIALOG} declared target fragment ColorPreferencesFragment{27e0e3b #0 id=0xffffffff .ColorPreferencesFragment} that does not belong to this FragmentManager!
```

My fragment looks like this:

```
class ColorPreferencesFragment: ChromaPreferenceFragmentCompat(){
    override fun onCreatePreferences(savedInstanceState: Bundle?, rootKey: String?) {
        // load your ChromaPreferenceCompat prefs from xml
        addPreferencesFromResource(R.xml.color_preferences)
    }
} 
```

and my targetSdkVersion is 27.

**Comment by J-Jamet** [comment]
After some tests, it seems to be an error of version 27. I look to solve the problem.

**Comment by J-Jamet** [comment]
OK, I have found a solution. I make a patch and create a new version in the day.
Previously, _getChildFragmentManager()_ was used to get sub FragmentManager in ChromaPreferenceFragmentCompat. It's now  _getFragmentManager()_. 
Tested with API 10, 16 and 27.

**Comment by J-Jamet** [comment]
Done in version 1.9. Don't hesitate to do a donation if the work is good for you. ;)
